"""Initial migration.

Revision ID: 86ac9304dad1
Revises: 
Create Date: 2021-04-25 13:17:30.678280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ac9304dad1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency_code', sa.String(length=3), nullable=True),
    sa.Column('target_currency_code', sa.String(length=3), nullable=True),
    sa.Column('rate', sa.Float(precision=4, asdecimal=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rate_base_currency_code'), 'fx_rate', ['base_currency_code'], unique=False)
    op.create_index(op.f('ix_fx_rate_target_currency_code'), 'fx_rate', ['target_currency_code'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('default_currency_code', sa.String(length=3), nullable=True),
    sa.Column('account_balance', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_fx_rate_target_currency_code'), table_name='fx_rate')
    op.drop_index(op.f('ix_fx_rate_base_currency_code'), table_name='fx_rate')
    op.drop_table('fx_rate')
    # ### end Alembic commands ###
