"""empty message

Revision ID: a538fe2f847b
Revises: 86ac9304dad1
Create Date: 2021-04-25 14:38:19.093073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a538fe2f847b'
down_revision = '86ac9304dad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('balance_after', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('amount', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('user_currency_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_currency_code', sa.String(length=3), nullable=False),
    sa.Column('date_transacted', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_date_transacted'), 'transaction', ['date_transacted'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_currency_code'), 'transaction', ['transaction_currency_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_currency_code'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date_transacted'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
