"""Add phone number details

Revision ID: abac33c8de61
Revises: a538fe2f847b
Create Date: 2021-06-24 10:32:23.765268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abac33c8de61'
down_revision = 'a538fe2f847b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_phone_number', sa.Unicode(length=255), nullable=True))
    op.add_column('user', sa.Column('phone_country_code', sa.Unicode(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_country_code')
    op.drop_column('user', '_phone_number')
    # ### end Alembic commands ###
